version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
